### ISSUE TITLE
[FIX] 블로그 코드 블록 줄바꿈 문제

### ISSUE THREAD

**Issue by 1lsang** [GDSC-CAU/GDSC-SPACE#132]
## Summary
블로그 탭의 코드블록 줄바꿈이 적용되지 않는 문제가 발생합니다.

## Description
다음과 같이 코드블록 내부의 줄바꿈이 작동하지 않고 한 줄로 나타납니다.

<img width="765" alt="스크린샷 2023-09-27 오후 11 09 41" src="https://github.com/GDSC-CAU/GDSC-SPACE/assets/74632599/22eda401-9fcd-4f25-8e4a-596a182bb4c3">

**Comment by danpacho** [comment]
<img width="675" alt="스크린샷 2023-09-30 오후 3 06 45" src="https://github.com/GDSC-CAU/GDSC-SPACE/assets/53421296/62dac647-f0d0-4b40-9d2e-a2a3be9f5213">

notion에 입력된 코드 블락이 그렇게 작성되어 있어서 발생한 문제 같습니다. 해당 이슈 있는 글은 추후 수정하면 될 것 같습니다.
