### ISSUE TITLE
[REFACTOR] 페이지가 의존하는 도메인 객체 타입의 모듈 분리 제안

### ISSUE THREAD

**Issue by minusmo** [GDSC-CAU/GDSC-SPACE#28]
## Summary
현재 app/ 하위의 각 페이지들은 각각 서로 다른 종류의 데이터에 종속성을 가집니다.(ex Event, Member)
이러한 데이터 타입(도메인 객체)이 page.tsx에 모듈 스코프를 가지고 있습니다. 
이 도메인 객체의 타입을 다른 모듈로 분리하는 것이 어떨까 합니다.
각 페이지가 정확히 하나의 도메인 객체에 종속적이라면 지금도 나쁘지 않지만,
하나 이상의 도메인 객체에 종속적이라면 코드가 혼잡해질 가능성이 있습니다.

## Description
- page.tsx에서 export하고 있는 도메인 객체 타입의 스코프를, 같은 디렉토리 레벨의 types/domain.ts 과 같은 모듈로 분리합니다.

**Comment by yymin1022** [comment]
이부분 안그래도 고려중이었습니다. 아직 API쪽이 구성이 안돼서 일단은 각 컴포넌트/페이지에서 정의하고 임시로 사용하도록 해두었는데,
이번주 내 API 백엔드 파트 작업하면서 따로 통합적으로 Interface랑 Type들을 정의하려고 합니다.
